/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  bookSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Part I: The Paradigm Shift',
      items: ['chapter-1-death-of-syntax', 'chapter-2-sdd'],
    },
    {
      type: 'category',
      label: 'Part II: The AI-Collaborative Workflow',
      items: ['chapter-3-conversational-codebase', 'chapter-4-agents-tools'],
    },
    {
      type: 'category',
      label: 'Part III: Architecture & Implementation',
      items: ['chapter-5-architecting-for-ai', 'chapter-6-guardrails'],
    },
    {
      type: 'category',
      label: 'Part IV: Production & Beyond',
      items: ['chapter-7-case-study', 'chapter-8-future'],
    },
  ],
};

export default sidebars;
